// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVy-JCguirlHauKQngLUhlCiwoVqQJQ7g',
    appId: '1:603466931207:web:4b1c20b47b45347a9a5ea2',
    messagingSenderId: '603466931207',
    projectId: 'medicalmatters-ba33f',
    authDomain: 'medicalmatters-ba33f.firebaseapp.com',
    storageBucket: 'medicalmatters-ba33f.appspot.com',
    measurementId: 'G-RMQYYFV2E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmkGJouorGLxDFACCYbcOab4f6L43hsXg',
    appId: '1:603466931207:android:be6b1ca09cfe08679a5ea2',
    messagingSenderId: '603466931207',
    projectId: 'medicalmatters-ba33f',
    storageBucket: 'medicalmatters-ba33f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8_vZpyPiiILjmEHld4zob7CWlLyl3oHY',
    appId: '1:603466931207:ios:233807ceeaadd97f9a5ea2',
    messagingSenderId: '603466931207',
    projectId: 'medicalmatters-ba33f',
    storageBucket: 'medicalmatters-ba33f.appspot.com',
    iosBundleId: 'com.example.medicalmatters',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8_vZpyPiiILjmEHld4zob7CWlLyl3oHY',
    appId: '1:603466931207:ios:233807ceeaadd97f9a5ea2',
    messagingSenderId: '603466931207',
    projectId: 'medicalmatters-ba33f',
    storageBucket: 'medicalmatters-ba33f.appspot.com',
    iosBundleId: 'com.example.medicalmatters',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVy-JCguirlHauKQngLUhlCiwoVqQJQ7g',
    appId: '1:603466931207:web:230d10fc5c736e6f9a5ea2',
    messagingSenderId: '603466931207',
    projectId: 'medicalmatters-ba33f',
    authDomain: 'medicalmatters-ba33f.firebaseapp.com',
    storageBucket: 'medicalmatters-ba33f.appspot.com',
    measurementId: 'G-HYKF3Z9GZ7',
  );
}
